
const NODE_SIZE_OPTIONS = {
    COOKIES: 0,
    DATA: 1
}

const LINK_THICK_OPTIONS = {
    COOKIES: 0,
    CALLS: 1
}

const NODE_COLOR_OPTIONS = {
    COOKIES: 0,
    CATEGORIES: 1
}

export {NODE_SIZE_OPTIONS, LINK_THICK_OPTIONS, NODE_COLOR_OPTIONS}